spring:
  application:
    name: UserSignIn
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/testing"
    username: "postgres"
    password: "mypassword"
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: create-drop

  session:
    jdbc:
      table-name: "SESSIONS"